### ISSUE TITLE
HUSER setting

### ISSUE THREAD

**Issue by pkuwm** [Open-Network-Insight/oni-docs#2]
In the setup scripts,
${hiveconf:huser} will be /user/soluser
and so '/user/${hiveconf:huser}/dns/hive' will be '/user/user/soluser/dns/hive'
This makes a bug and cannot create hive tables.
LOCATION '/user/${hiveconf:huser}/dns/hive'

**Comment by grantbabb** [comment]
indeed a bug, moving to open-network-insight repo and marking 'help wanted'
